name: Check qa passed label on Pull Requests

on:
  pull_request:
    types: [opened,labeled, unlabeled]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "qa passed" label
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name.toLowerCase());
            if (labels.includes("qa passed")) {
              console.log("qa passed label exists on the pull request.");
            } else {
              console.log("qa passed label does not exist on the pull request.");
              core.setFailed("qa passed label does not exist on the pull request.");
            }
